[project]
name = "scaling-crl"
version = "0.1.0"
description = "1000 Layer Networks for Self-Supervised RL: Scaling Depth Can Enable New Goal-Reaching Capabilities"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "numpy>=2.2,<3",
    "jax[cuda12]==0.6.2; platform_system == 'Linux'",
    "jax==0.6.2; platform_system != 'Linux'",
    "flax==0.10.7",
    "optax==0.2.5",
    "tyro",
    "hydra-core>=1.3.2,<2",
    "hydra-submitit-launcher>=1.2.0,<2",
    "wandb>=0.19,<0.20",
    "wandb-osh==1.2.2",
    "brax==0.14.2",
    "mediapy>=1.2,<2",
    "scipy>=1.15,<2",
    "mujoco==3.8.0",
    "mujoco-mjx==3.8.0",
    "warp-lang==1.12.1",
    "playground==0.2.0",
    "ogbench==1.2.1",
    "gymnasium>=1.3,<2",
    "ml-collections>=1.1,<2",
    "pillow>=12,<13",
    "imageio-ffmpeg>=0.6,<0.7",
]

[tool.uv]
package = false
